Ifu20240625 group gemm yewang12
ROCm/TransformerEngine pull request #59
Opened 2024-09-19 16:25 UTC by wangye805

# Description

Please include a brief summary of the changes, relevant motivation and context.

Fixes # (issue)

## Type of change

- [ ] Documentation change (change only to the documentation, either a fix or a new content)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Infra/Build change
- [ ] Code refractor

## Changes

Please list the changes introduced in this PR:

- a4e95e86: the first commit for grouped linear from our upstream
- Change B

# Checklist:

- [ ] I have read and followed the [contributing guidelines](https://github.com/NVIDIA/TransformerEngine/blob/main/CONTRIBUTING.rst)
- [x] The functionality is complete
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2024-10-07 21:29 UTC, ipanfilo requested changes

2024-10-07 21:29 UTC, ipanfilo commented on tests/pytorch/fused_attn/test_fused_attn.py
> +    if IS_HIP_EXTENSION:
This code duplicates skipif from line 1706

2024-10-07 21:29 UTC, ipanfilo commented on tests/pytorch/fused_attn/test_fused_attn.py
> +    if IS_HIP_EXTENSION:
It duplicates skipif from line 1494

2024-10-07 21:29 UTC, ipanfilo commented on tests/pytorch/fused_attn/test_fused_attn_with_cp.py
> -@pytest.mark.parametrize("dtype", ["bf16", "fp16"])
This change is not needed  -  it's just reverting of corresponding upstream changes.

2024-10-07 21:29 UTC, ipanfilo commented on tests/pytorch/test_sanity.py
> +@pytest.mark.skipif(get_device_compute_capability() != (9, 0), reason="FP8 tests require Hopper.")
Need to be (not IS_HIP_EXTENSION and get_device...) to enable the test on ROCm or (IS_HIP_EXTENSION or ....) to disable

2024-10-07 21:29 UTC, ipanfilo commented on build_tools/build_ext.py
> -                    setup_dir = Path(__file__).resolve().parent
This seems to be the only functuinal change in this file, all others are format reverting

2024-10-07 21:29 UTC, ipanfilo commented on transformer_engine/jax/cpp_extensions/attention.py
> -                raise ValueError(f"Unsupported {backend=}")
All jax/cpp_extension changes seem format reverting

2024-10-08 15:52 UTC, wangye805 commented on tests/pytorch/fused_attn/test_fused_attn.py
> +    if IS_HIP_EXTENSION:
Done

2024-10-08 15:52 UTC, wangye805 commented on tests/pytorch/fused_attn/test_fused_attn.py
> +    if IS_HIP_EXTENSION:
Done

2024-10-08 15:53 UTC, wangye805 commented on tests/pytorch/fused_attn/test_fused_attn_with_cp.py
> -@pytest.mark.parametrize("dtype", ["bf16", "fp16"])
Done.

2024-10-08 15:53 UTC, wangye805 commented on tests/pytorch/test_sanity.py
> +@pytest.mark.skipif(get_device_compute_capability() != (9, 0), reason="FP8 tests require Hopper.")
Done

2024-10-08 15:53 UTC, wangye805 commented on build_tools/build_ext.py
> -                    setup_dir = Path(__file__).resolve().parent
Done

2024-10-08 15:53 UTC, wangye805 commented on transformer_engine/jax/cpp_extensions/attention.py
> -                raise ValueError(f"Unsupported {backend=}")
Done

2024-10-08 20:00 UTC, ipanfilo commented on transformer_engine/pytorch/attention.py
> +                    use_flash_attention
Since it checks for use_flash_attention it does not need to be under else codepath and may remain untouched like other if (use_flash_attention...) conditions above.
Also, use_flash_attention=False from line 5001 may be moved higher - somewhere above line 4929 (4901 together with fused_attn?) so no further checks/warnings about disabling it are made on ROCm path.

2024-10-09 02:41 UTC, wangye805 commented on transformer_engine/pytorch/attention.py
> +                    use_flash_attention
Done

2024-10-09 06:04 UTC, ipanfilo requested changes

2024-10-09 06:04 UTC, ipanfilo commented on 3rdparty/cudnn-frontend
This does not match upstream version which is the same as in current dev

2024-10-09 06:05 UTC, ipanfilo commented
Except CUDNN the code looks good for me.

2024-10-09 15:01 UTC, wangye805 commented on 3rdparty/cudnn-frontend
Good catch! Just fixed.

2024-10-09 17:05 UTC, ipanfilo approved these changes

2024-10-14 19:03 UTC, merged