Update supported tests in README.rst
ROCm/TransformerEngine pull request #61
Opened 2024-09-24 14:31 UTC by ipanfilo

## Type of change

- [ ] Documentation change (change only to the documentation, either a fix or a new content)

2024-09-24 15:01 UTC, wangye805 requested changes

2024-09-24 15:01 UTC, wangye805 commented on README.rst
> +  export NVTE_FRAMEWORK=pytorch,jax #optionally set framework, currently only support pytorch and jax; if not set will try to detect installed frameworks
Have you tested whether it can detect installed frameworks? I never tested before

2024-09-24 15:01 UTC, wangye805 commented on README.rst
> -It can be dropped when the hipGraph feature is fully supported in Pytorch on AMDGPUs.
Emm, do we support test_cuda_graph.py in hipblaslt configuration?

2024-09-24 15:01 UTC, wangye805 commented on README.rst
> -It can be dropped when the hipGraph feature is fully supported in Pytorch on AMDGPUs.
BTW, how about test_convergence.py and the .so generation in test_onnx_export.py?

2024-09-24 16:07 UTC, ipanfilo commented on README.rst
> +  export NVTE_FRAMEWORK=pytorch,jax #optionally set framework, currently only support pytorch and jax; if not set will try to detect installed frameworks
Yes, I did

2024-09-24 16:11 UTC, ipanfilo commented on README.rst
> -It can be dropped when the hipGraph feature is fully supported in Pytorch on AMDGPUs.
We support test_cuda_graph with hipblaslt. 
About test_convergence you were right - it does nothing w/o data. QA section contains test script that downloads Megathron-LM and uses test_convergence but it does rely on existing data too. So I cannot confirm whether it works for us or not.
FP8 custom q/dq ops for ONNX - I did not find source of it so nothing to port to us. Making it from scratch requires better knowledge of ONNX

2024-09-24 19:11 UTC, wangye805 commented on README.rst
> -It can be dropped when the hipGraph feature is fully supported in Pytorch on AMDGPUs.
Thanks for the confirmation.

I recall test_cuda_graph tested mha and dpa, which may call our rocm fused attn backends. But CK and AOTriton have not supported cuda graph yet. Do you mean it passes with NVTE_FUSED_ATTN=0?

We probably need to mention those tricky points in our README

2024-09-24 19:12 UTC, wangye805 commented on README.rst
> +  export NVTE_FRAMEWORK=pytorch,jax #optionally set framework, currently only support pytorch and jax; if not set will try to detect installed frameworks
Oh, great to know!

2024-09-24 19:13 UTC, wangye805 requested changes
Let's mention those tricky scenarios (test_cuda_graph, test_onnx_export, and test_convergence)

2024-09-24 21:52 UTC, ipanfilo commented on README.rst
> -It can be dropped when the hipGraph feature is fully supported in Pytorch on AMDGPUs.
Test_cuda_graph indeed tests dpa and uses fused attn_backend. It however works with both CK and AOTriton. So they rather partially support cuda_graph than don't support at all.

2024-09-26 16:25 UTC, wangye805 commented on README.rst
> -It can be dropped when the hipGraph feature is fully supported in Pytorch on AMDGPUs.
Thanks for the confirmation. Please help confirm whether the dropout probability is 0 or not?

2024-09-27 05:14 UTC, wangye805 commented on README.rst
> -It can be dropped when the hipGraph feature is fully supported in Pytorch on AMDGPUs.
Okay, I saw the dropout prob are all 0 in test_cuda_graph.py: https://github.com/ROCm/TransformerEngine/blob/285163a24a5472641cffc1ebb91a56b22fe9c3e2/tests/pytorch/test_cuda_graphs.py#L177-L190. Therefore, it's expected that this test can pass with our current rocm fused attn backends.

How about test_convergence.py and test_onnx_export.py? Let's mention the tricky points we discussed?

2024-09-27 05:17 UTC, wangye805 approved these changes
Overall LGTM. 
Minor issues: to mention tricky points in test_convergence.py and test_onnx_runtime.py

2024-09-27 12:10 UTC, ipanfilo commented on README.rst
> -It can be dropped when the hipGraph feature is fully supported in Pytorch on AMDGPUs.
Confirmed from test code and by debugging attention that dropout is non-zero in test_numeric and 0 in test_cuda_graph. 
Also those tests use QKV memory layout.

But what about test_convergence? It is not in the list of supported tests.

2024-09-27 12:50 UTC, merged

2024-09-27 15:44 UTC, wangye805 commented on README.rst
> -It can be dropped when the hipGraph feature is fully supported in Pytorch on AMDGPUs.
Oh I see, it's in tests/pytorch/distributed. Nevermind