Ifu release v1.9
ROCm/TransformerEngine pull request #66
Opened 2024-10-07 22:40 UTC by wangye805

# Description

IFU to upstream release v1.9

## Type of change

- [ ] Documentation change (change only to the documentation, either a fix or a new content)
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Infra/Build change
- [ ] Code refractor

## Changes
IFU to upstream release v1.9

# Checklist:

- [x] I have read and followed the [contributing guidelines](https://github.com/NVIDIA/TransformerEngine/blob/main/CONTRIBUTING.rst)
- [x] The functionality is complete
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2024-10-15 22:42 UTC, ipanfilo requested changes
Can you please merge dev back to this PR. It contains many changes that have been reviewed in Grouped_gemm IFU

2024-10-15 22:42 UTC, ipanfilo commented on 3rdparty/cudnn-frontend
This is wrong update of component version back to very old one

2024-10-15 22:42 UTC, ipanfilo commented on build_tools/build_ext.py
> +                self.compiler.src_extensions += ['.cu', '.cuh', '.hip']
Formatting reversion

2024-10-15 22:42 UTC, ipanfilo commented on build_tools/build_ext.py
> +                            self.compiler.set_executable('compiler_so', str(nvcc_bin))
Formatting reversion

2024-10-15 22:42 UTC, ipanfilo commented on build_tools/build_ext.py
> +                                    cflags.append('--forward-unknown-opts')
Formatting reversion

2024-10-15 22:42 UTC, ipanfilo commented on tests/pytorch/fused_attn/test_fused_attn_with_cp.py
> +    get_cudnn_version,
Please keep at least get_cudnn_version under 'if not IS_HIP_EXTENSION'

2024-10-15 22:42 UTC, ipanfilo commented on tests/pytorch/fused_attn/test_fused_attn_with_cp.py
> +@pytest.mark.skipif(get_device_compute_capability() < (8, 0), reason="CP tests require sm80+.")
IS_HIP_EXTENSION should be checked

2024-10-15 22:46 UTC, wangye805 commented on build_tools/build_ext.py
> +                self.compiler.src_extensions += ['.cu', '.cuh', '.hip']
Emm, are you looking at my latest version? From my side, it does not have those diffs: 
![image](https://github.com/user-attachments/assets/6c8c2446-1880-4f3a-ac9c-536fdf66a289)

2024-10-15 22:49 UTC, wangye805 commented on 3rdparty/cudnn-frontend
This one is the same as NVTE upstream release v1.9: 
<img width="1894" alt="image" src="https://github.com/user-attachments/assets/b0e0e69a-b5c2-4156-81e6-3a743f90afff">

2024-10-15 22:49 UTC, wangye805 commented on build_tools/build_ext.py
> +                self.compiler.src_extensions += ['.cu', '.cuh', '.hip']
Same as above

2024-10-15 22:49 UTC, wangye805 commented on build_tools/build_ext.py
> +                            self.compiler.set_executable('compiler_so', str(nvcc_bin))
Same

2024-10-15 22:49 UTC, wangye805 commented on build_tools/build_ext.py
> +                                    cflags.append('--forward-unknown-opts')
Same

2024-10-15 22:51 UTC, wangye805 commented on tests/pytorch/fused_attn/test_fused_attn_with_cp.py
> +    get_cudnn_version,
I follow your idea to make our cudnn version (99, 0, 0) to minimize our difference:
https://github.com/ROCm/TransformerEngine/blob/1a79df4bdabda712ba53585360a6eed5116e9bff/transformer_engine/pytorch/utils.py#L263-L267

2024-10-15 22:53 UTC, wangye805 commented on tests/pytorch/fused_attn/test_fused_attn_with_cp.py
> +@pytest.mark.skipif(get_device_compute_capability() < (8, 0), reason="CP tests require sm80+.")
Similarly, I put our flash attn version to be (0, 0, 1) so we can minimize the code difference: https://github.com/ROCm/TransformerEngine/blob/1a79df4bdabda712ba53585360a6eed5116e9bff/transformer_engine/pytorch/attention.py#L78-L89

2024-10-16 15:03 UTC, ipanfilo requested changes

2024-10-16 15:03 UTC, ipanfilo commented on transformer_engine/common/CMakeLists.txt
> +target_compile_definitions(transformer_engine PUBLIC NV_CUDNN_FRONTEND_USE_DYNAMIC_LOADING)
Should it be under USE_CUDA?

2024-10-16 15:03 UTC, ipanfilo commented on transformer_engine/common/nvtx.h
> +#else
Should we add this to custom hipify map? I think eventually it should be incorporated to default mapping

2024-10-16 15:03 UTC, ipanfilo commented on transformer_engine/common/util/cuda_driver.cpp
> +  NVTE_CHECK_CUDA(hipGetProcAddress(symbol, &entry_point, 602, 0, &driver_result));
Should HIP_VERSION_MAJOR*100 + HIP_VERSION_MINOR be used instead of hard coded 602?

2024-10-16 15:03 UTC, ipanfilo commented on transformer_engine/pytorch/attention.py
> +    if device_compute_capability < (8, 0):
IS_HIP_EXTENSION should be checked here

2024-10-16 15:03 UTC, ipanfilo commented on tests/pytorch/fused_attn/test_fused_attn_with_cp.py
> +@pytest.mark.skipif(get_device_compute_capability() < (8, 0), reason="CP tests require sm80+.")
It is fine for FA version check but get_device_compute_capability should still be guarded

2024-10-17 19:06 UTC, wangye805 commented on transformer_engine/common/nvtx.h
> +#else
It's not a custom hipify issue. I think it's nvtx3 issue. With __HIP_PLATFORM_AMD__, we need <nvToolsExt.h> which will be hipified into <roctracer/roctx.h>.

2024-10-17 19:06 UTC, wangye805 commented on transformer_engine/common/util/cuda_driver.cpp
> +  NVTE_CHECK_CUDA(hipGetProcAddress(symbol, &entry_point, 602, 0, &driver_result));
Done

2024-10-17 19:07 UTC, wangye805 commented on transformer_engine/pytorch/attention.py
> +    if device_compute_capability < (8, 0):
Done

2024-10-17 19:07 UTC, wangye805 commented on transformer_engine/common/CMakeLists.txt
> +target_compile_definitions(transformer_engine PUBLIC NV_CUDNN_FRONTEND_USE_DYNAMIC_LOADING)
Done

2024-10-17 19:07 UTC, wangye805 commented on tests/pytorch/fused_attn/test_fused_attn_with_cp.py
> +@pytest.mark.skipif(get_device_compute_capability() < (8, 0), reason="CP tests require sm80+.")
Done

2024-10-17 20:13 UTC, ipanfilo commented on transformer_engine/common/nvtx.h
> +#else
But should <nvtx3/nvToolsExt.h> be also hipified to <roctracer/roctx.h> like <nvToolsExt.h>? The ifdefs make hipified code explicitly using <roctracer/roctx.h> that can also be achieved by adding <nvtx3/nvToolsExt.h> ->  <roctracer/roctx.h> hipify mapping.

2024-10-17 21:24 UTC, wangye805 commented on transformer_engine/common/nvtx.h
> +#else
Done

2024-10-18 02:24 UTC, ipanfilo approved these changes

2024-10-21 19:04 UTC, merged