Wen/opt cast transpose noop
ROCm/TransformerEngine pull request #83
Opened 2024-10-24 05:35 UTC by wenchenvincent

# Description
Added Triton kernels for fp8 cast transpose to improve performance over hipified kernels.

## Type of change

- [ ] Documentation change (change only to the documentation, either a fix or a new content)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Infra/Build change
- [ ] Code refractor

2024-11-02 22:04 UTC, wangye805 requested changes
Overall LGTM, some minor issues

2024-11-02 22:04 UTC, wangye805 commented on tests/pytorch/test_cast_transpose_triton.py
> +@pytest.mark.parametrize("M, N, in_dtype, out_dtype",
Using this way of parameterize will print in_dtype0, in_dtype1, and so on, instead of torch.float32 when you run pytest -s -v. Can you rewrite it as 
@pytest.mark.parametrize("M, N", [<shapes lists>])
@pytest.mark.parametrize("in_dtype", [torch.float32, torch.bfloat16, torch.bfloat16])
@pytest.mark.parametrize("out_dtype", [torch.float8_e4m3fnuz, torch.float8_e5m2fnuz])

2024-11-02 22:04 UTC, wangye805 commented on transformer_engine/pytorch/cpp_extensions/transpose.py
> +                # TODO: Check if it is Okay to do that...
Remove this TODO and commented scale_inv line?

2024-11-02 22:04 UTC, wangye805 commented on transformer_engine/pytorch/cpp_extensions/transpose.py
> +            # TODO: Check if it is Okay to do that...
Same here

2024-11-03 21:40 UTC, wenchenvincent commented on tests/pytorch/test_cast_transpose_triton.py
> +@pytest.mark.parametrize("M, N, in_dtype, out_dtype",
It seems that it would still print in_dtype0 even if I rewrite it.

2024-11-03 23:46 UTC, wangye805 commented on tests/pytorch/test_cast_transpose_triton.py
> +@pytest.mark.parametrize("M, N, in_dtype, out_dtype",
Below is what shows on my end with your current parameterize code: 
<img width="743" alt="image" src="https://github.com/user-attachments/assets/05a159df-2833-4ab1-8092-94248afc1cdf">
We only have 3 in_dtypes but here it shows a lot. 

After changing to the way I suggested, it becomes:
<img width="886" alt="image" src="https://github.com/user-attachments/assets/4a662943-3e32-4256-901e-b1ede3cf3dc5">

2024-11-04 01:34 UTC, wenchenvincent commented on tests/pytorch/test_cast_transpose_triton.py
> +@pytest.mark.parametrize("M, N, in_dtype, out_dtype",
Oh, right. Updated.

2024-11-04 01:34 UTC, wenchenvincent commented on transformer_engine/pytorch/cpp_extensions/transpose.py
> +                # TODO: Check if it is Okay to do that...
Done.

2024-11-04 01:34 UTC, wenchenvincent commented on transformer_engine/pytorch/cpp_extensions/transpose.py
> +            # TODO: Check if it is Okay to do that...
Done.

2024-11-04 05:17 UTC, wangye805 approved these changes

2024-11-04 17:30 UTC, merged