add new branch heyi_cast_transpose and update cast_transpose optimizations
ROCm/TransformerEngine pull request #89
Opened 2024-11-04 13:43 UTC by eliotwang

# Description

Optimize the cast_transpose kernel by:
1. refactoring the kernel to support more flexible parameter tuning methods; 
2. use assembly instructions to optimize the conversion for fp8 output types; 
3. apply performance analysis on different input shapes and provide empirical parameter configuration methods, ensuring that the HIP kernel's performance exceeds Triton's performance in all tests;

# Steps to run:
docker pull rocm/pytorch:latest

docker run -it --network=host -v /home/yigex/heyi:/workspace --device=/dev/kfd --device=/dev/dri --group-add video --security-opt seccomp=unconfined --ipc=host --name heyi_te_wx rocm/pytorch:latest

mkdir heyi && cd heyi

git clone -b heyi_cast_transpose --recursive https://github.com/eliotwang/TransformerEngine.git

cd TransformerEngine

export NVTE_FRAMEWORK=pytorch
export NVTE_ROCM_ARCH=gfx942

pip install .

mkdir tests/cpp/build && cd tests/cpp/build

cmake .. && make

./operator/test_operator

[ RUN      ] OperatorTest/CTTestSuite.TestCastTranspose/bfloat16Xfloat8e5m2X2048X12288
GPU execution time: 54.7456 us
[       OK ] OperatorTest/CTTestSuite.TestCastTranspose/bfloat16Xfloat8e5m2X2048X12288 (2854 ms)
[ RUN      ] OperatorTest/CTTestSuite.TestCastTranspose/bfloat16Xfloat8e5m2X256X65536
GPU execution time: 39.4748 us
[       OK ] OperatorTest/CTTestSuite.TestCastTranspose/bfloat16Xfloat8e5m2X256X65536 (1690 ms)

# Performance:
![image](https://github.com/user-attachments/assets/6e887279-420d-46a2-923c-7da818931f8c)

2024-11-04 22:01 UTC, wenchenvincent commented on tests/cpp/operator/test_cast_transpose.cu
> +  int warm_iter = 3;
I suggest that we keep this test file as is. This file was just for unit testing. We can measure performance when running it with rocprof.

2024-11-05 06:03 UTC, wenchenvincent commented on transformer_engine/common/transpose/cast_transpose.cu
> +            size_t store_size;
We would like to keep the original NVTE CUDA code while adding the new code for ROCm. You can use `__HIP_PLATFORM_AMD__` to guard the code. Here is an example: https://github.com/ROCm/TransformerEngine/blob/dev/transformer_engine/common/fused_softmax/scaled_masked_softmax.cu#L72-L80

2024-11-05 06:08 UTC, wenchenvincent commented on transformer_engine/common/transpose/rtc/cast_transpose.cu
> +__device__ OType convert_from_fp32(float v) {
What's the key difference between this function and https://github.com/ROCm/TransformerEngine/blob/dev/transformer_engine/common/amd_detail/hip_float8.h?

2024-11-07 11:36 UTC, eliotwang commented on transformer_engine/common/transpose/rtc/cast_transpose.cu
> +__device__ OType convert_from_fp32(float v) {
This function appears to be more complete. When compiling with the __gfx940__ macro enabled, it results in an error related to function overloading

2024-11-11 12:55 UTC, eliotwang commented
1. Revert the tests/cpp/operator/test_cast_transpose.cu to its original version;
2. Add __HIP_PLATFORM_AMD__ to guard modified code in transformer_engine/common/transpose/cast_transpose.cu;
3. Modify hip_f8 funcs in hip_float8.h to ensure the code runs correctly on MI308X;
4. Adopt hip_f8 funcs in hip_float8.h to do precision conversion and remove custom conversion functions;

2024-11-14 12:02 UTC, eliotwang commented
fix cast_transpose issue where the width and height of the tensor cannot be divided by the tile size. pass pytest including test_float8tensor.py，test_numerics.py，fused_attn/test_fused_attn.py and test_sanity.py

2025-01-07 23:40 UTC, wangye805 requested changes
Sorry for the late review. 

I was only able to review the cast_transpose part, not the cast_transpose_fusion part. I gave some comments on the coding style. But I'm still quite confused about the big picture as how wpt_size, iter_size works.

2025-01-07 23:40 UTC, wangye805 commented on transformer_engine/common/transpose/cast_transpose.cu
> +            size_t store_size;
+1

Line 280 to 286 should also be guarded by #ifdef __HIP_PLATFORM_AMD__. 

Basically, after removing the rocm/amd specific ifdefs, we would like to see our repo are exactly the same as the upstream NVTE

2025-01-07 23:40 UTC, wangye805 commented on transformer_engine/common/transpose/cast_transpose.cu
> +            if((std::is_same<OutputType, fp8e5m2>::value) || (std::is_same<OutputType, fp8e4m3>::value)){
can use if constexpr since OutputType is determined at compile time

2025-01-07 23:40 UTC, wangye805 commented on transformer_engine/common/transpose/cast_transpose.cu
> +                size_t nvec_out = store_size / sizeof(OutputType);
Actually the sizeof(OutputType) is already fixed under this if condition

2025-01-07 23:40 UTC, wangye805 commented on transformer_engine/common/transpose/cast_transpose.cu
> +              return n_tiles;
Should be the same indent as line 301

2025-01-07 23:40 UTC, wangye805 commented on transformer_engine/common/transpose/cast_transpose.cu
> +              return n_blocks;
indent issue

2025-01-07 23:40 UTC, wangye805 commented on transformer_engine/common/transpose/cast_transpose.cu
> +              do_general_config =!(row_length % row_tile_elements == 0 && num_rows % col_tile_elements == 0);
do_general_config is just not aligned()?

2025-01-07 23:40 UTC, wangye805 commented on transformer_engine/common/transpose/cast_transpose.cu
> +              add_config(8, 8);
Regarding the big picture, in my opinion, you are trying to introduce a wpt_size and a iter_size so that wpt_size * iter_size <= THREADS_PER_WARP, in contrast to warps_per_tile x num_interations = THREADS_PER_WARP. So that each thread can save some registers and overall shared mems. Is my understanding correct? 

If so, I would expect add_config() will add wpt_size and iter_size into the cost model. But here we don't see additional parameters for add_config. Why?

2025-01-07 23:40 UTC, wangye805 commented on transformer_engine/common/transpose/cast_transpose.cu
> +              iter_size = THREADS_PER_WARP / wpt_size;
if iter_size x wpt_size = THREADS_PER_WARP here, why do we need to add ITER_SIZE into the subsequent RTC params?

2025-01-08 12:11 UTC, zora-my commented on transformer_engine/common/transpose/cast_transpose.cu
> +              iter_size = THREADS_PER_WARP / wpt_size;
This is an added parameter for optimization, aimed at testing the impact of different wpt_size and iter_size configurations on performance.

2025-01-08 12:25 UTC, zora-my commented on transformer_engine/common/transpose/cast_transpose.cu
> +              do_general_config =!(row_length % row_tile_elements == 0 && num_rows % col_tile_elements == 0);
Under the AMD framework, if the output type is FP8 and the current tile_size meets certain conditions, the optimized configuration will be used; otherwise, it will fall under the do_general_config case.

2025-01-09 04:09 UTC, zora-my commented on transformer_engine/common/transpose/cast_transpose.cu
> +              add_config(8, 8);
Yes, when wpt_size * iter_size <= THREADS_PER_WARP, it can save some registers and overall shared memory, thus improving the occupancy of the cu. How can we reflect the impact of wpt_size and iter_size on performance improvement in the cost model?

2025-01-09 17:39 UTC, wangye805 commented on transformer_engine/common/transpose/cast_transpose.cu
> +              add_config(8, 8);
Emm, we probably first need to understand how latency is affected by wpt_size*iter_size before changing the cost model. 

By the way, from https://github.com/eliotwang/TransformerEngine/blob/b9359d65666bbcbd6734376e180c8fbe513c50ee/transformer_engine/common/transpose/cast_transpose.cu#L312, it seems that wpt_size*iter_size is still tied to THREADS_PER_WARP, which is 32?

2025-04-01 03:42 UTC, wangye805 commented on transformer_engine/common/transpose/cast_transpose.cu
> +              do_general_config = false;
This do_general_config assignment will be overwritten by line 329. Let's remove it?

2025-04-01 03:46 UTC, wangye805 commented on transformer_engine/common/transpose/cast_transpose.cu
> +              const size_t estimated_n_blocks = get_n_blocks(estimated_n_tiles, cast_transpose_num_threads, wpt_size);
After digesting these three lines, I found that n_blocks is just n_tiles since 
n_blocks = n_tiles * wpt_size/ (wpt_size*threads_per_warp/threads_per_warp) = n_tiles

So can we help clean those up?

2025-04-01 03:48 UTC, wangye805 commented on transformer_engine/common/transpose/cast_transpose.cu
> +            if(do_general_config){
No matter what do_general_config is assigned to in line 329, we will launch a rtc kernel for this case. What if do_general_config is true? Then it will launch another general tuning kernel. Does that mean we will run two kernels for the one case?

2025-04-01 03:54 UTC, wangye805 commented on transformer_engine/common/transpose/cast_transpose.cu
> +              rtc_manager.launch(kernel_label, num_blocks, rtc_block_size, 0, stream,
This fails TE pytorch pytests  tests/pytorch/test_numerics.py::test_grouped_linear_accuracy[True-True-126m-1-6-dtype0]

To reproduce, we can run the following command: 
HEYI_CAST_TRANSPOSE=1 pytest -s -v tests/pytorch/test_numerics.py::test_grouped_linear_accuracy[True-True-126m-1-6-dtype0] 

I dived a little into this failure, it seems that for the case that row_length: 768, num_rows: 96,  this rtc manager will try to launch a kernel with num_blocks = 0

2025-04-03 09:59 UTC, zora-my commented on transformer_engine/common/transpose/cast_transpose.cu
> +              const size_t estimated_n_blocks = get_n_blocks(estimated_n_tiles, cast_transpose_num_threads, wpt_size);
Yes, we have cleaned it up in the new PR.

2025-04-03 10:08 UTC, zora-my commented on transformer_engine/common/transpose/cast_transpose.cu
> +            if(do_general_config){
Thank you for your feedback. The current logic here is incorrect. The correct behavior should be: only when do_general_config=false will the tuned kernel be invoked; otherwise, the original kernel will be executed.

2025-04-03 10:09 UTC, zora-my commented on transformer_engine/common/transpose/cast_transpose.cu
> +              rtc_manager.launch(kernel_label, num_blocks, rtc_block_size, 0, stream,
This is due to the logical error with do_general_config earlier. When the shape is [768, 96], it should call the original RTC kernel, but it is currently calling the tuning kernel, which causes the execution to fail.

2025-04-10 02:47 UTC, wangye805 approved these changes
LGTM

2025-04-10 15:06 UTC, merged