Ifu release v1.11 nov
ROCm/TransformerEngine pull request #95
Opened 2024-11-26 18:12 UTC by wangye805

# Description

IFU to upstream NVTE release v1.11 based on current dev (v1.9)

Some jax pytests are failing:
1). test_layer.py: due to https://ontrack-internal.amd.com/browse/SWDEV-499638
2). test_distributed_fused_attn.py: due to https://ontrack-internal.amd.com/browse/SWDEV-482895
3). test_distributed_softmax.py: memory segmentation fault under investigation
4). test_distributed_layernorm_mlp: hipblaslt issue met before in ticket SWDEV-482895
5). test_praxis_layer.py: not able to find a compatible praxis installation

## Type of change

- [x] Documentation change (change only to the documentation, either a fix or a new content)
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Infra/Build change
- [x] Code refractor

## Changes

1). Merge commit 377252
2). Resolving commit 2b6dc5f9

# Checklist:

- [x] I have read and followed the [contributing guidelines](https://github.com/NVIDIA/TransformerEngine/blob/main/CONTRIBUTING.rst)
- [x] The functionality is complete
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2024-11-27 21:07 UTC, ipanfilo requested changes

2024-11-27 21:07 UTC, ipanfilo commented on build_tools/utils.py
> -import importlib.metadata
Importlib.metadata is used to detect ROCm support in JAX. How does it build on JAX with this import removed

2024-11-27 21:07 UTC, ipanfilo commented on build_tools/utils.py
> +    if rocm_build():
This methods seems used only for CUDA builds. Why does it need ROCm code path?

2024-11-27 21:07 UTC, ipanfilo commented on tests/pytorch/fused_attn/test_fused_attn_with_cp.py
> -@pytest.mark.skipif(device_count() < 2, reason="multi-GPU host is required")
This condition is added by us to avoid test failures. Does the test pass now with single GPU?

2024-11-27 21:07 UTC, ipanfilo commented on tests/pytorch/fused_attn/test_fused_attn_with_cp.py
>      if qkv_format == "thd" and get_device_compute_capability() < (9, 0):
Maybe not part of this PR but get_device_compute_capability checking should be guarded by ROCm/CUDA selection - compute capabilities are different between AMD and NV GPUs

2024-11-27 21:07 UTC, ipanfilo commented on transformer_engine/common/CMakeLists.txt
> +       util/padding.cu
Is it added for ROCm but not CUDA?

2024-11-27 21:07 UTC, ipanfilo commented on tests/pytorch/fused_attn/test_fused_attn_with_cp.py
> -@pytest.mark.skipif(device_count() < 2, reason="multi-GPU host is required")
This condition is added by us to avoid test failures. Does the test pass now with single GPU?

2024-11-27 21:07 UTC, ipanfilo commented on transformer_engine/jax/__init__.py
> +        ), "Could not find `transformer-engine-cu12`."
Do ROCm dockers have this package?

2024-11-27 21:07 UTC, ipanfilo commented on transformer_engine/common/fused_attn_rocm/fused_attn_aotriton.cpp
> +  //TODO: release after AOTriton support support Multi-latent attention
Multi-head latent?

2024-11-27 21:07 UTC, ipanfilo commented on transformer_engine/common/CMakeLists.txt
> +  set(CMAKE_CUDA_FLAGS "${CMAKE_CUDA_FLAGS} -Wl,--version-script=${CMAKE_CURRENT_SOURCE_DIR}/libtransformer_engine.version")
It may make sense to use version-script for ROCm build too

2024-11-27 21:07 UTC, ipanfilo commented on transformer_engine/common/permutation/permutation.cu
> +/*************************************************************************
AMD copyright should be added since the file is modified for ROCm compilation

2024-11-27 21:07 UTC, ipanfilo commented on transformer_engine/jax/cpp_extensions/activation.py
> +from jax.extend import ffi
Do we switch to jax 0.4.31 after this PR or should still support 0.4.23? I think this will cause error on the latter

2024-11-27 21:07 UTC, ipanfilo commented on transformer_engine/jax/csrc/extensions/ffi.cpp
> +/*************************************************************************
Add AMD copyright

2024-11-27 21:07 UTC, ipanfilo commented on transformer_engine/pytorch/csrc/extensions/multi_tensor/multi_tensor_adam.cu
Add AMD copyright

2024-11-27 21:07 UTC, ipanfilo commented on transformer_engine/pytorch/csrc/type_shim.h
> -constexpr uint32_t THREADS_PER_WARP = 32;
Why is it removed here?

2024-12-05 15:35 UTC, ipanfilo commented on transformer_engine/jax/cpp_extensions/activation.py
> +from jax.extend import ffi
NVM, got an answer offline

2024-12-05 15:42 UTC, ipanfilo commented on transformer_engine/common/CMakeLists.txt
> +  set(CMAKE_CUDA_FLAGS "${CMAKE_CUDA_FLAGS} -Wl,--version-script=${CMAKE_CURRENT_SOURCE_DIR}/libtransformer_engine.version")
Made it part of ROCm build in [PR96](https://github.com/ROCm/TransformerEngine/pull/96)

2024-12-09 04:34 UTC, wangye805 commented on build_tools/utils.py
> -import importlib.metadata
Based on this line (https://github.com/ROCm/TransformerEngine/blob/2b6dc5f9f77572dcab27c0fc63a57fd502e44462/build_tools/utils.py#L316), we should be fine after importlib is imported

2024-12-09 04:39 UTC, wangye805 commented on build_tools/utils.py
> +    if rocm_build():
Thanks for pointing out. Fixed.

2024-12-09 04:43 UTC, wangye805 commented on tests/pytorch/fused_attn/test_fused_attn_with_cp.py
> -@pytest.mark.skipif(device_count() < 2, reason="multi-GPU host is required")
Added back. Thanks for pointing out

2024-12-09 04:49 UTC, wangye805 commented on tests/pytorch/fused_attn/test_fused_attn_with_cp.py
>      if qkv_format == "thd" and get_device_compute_capability() < (9, 0):
Fixed. Thanks

2024-12-09 04:49 UTC, wangye805 commented on transformer_engine/common/CMakeLists.txt
> +       util/padding.cu
No. My mistake missing adding it to cuda side

2024-12-09 04:50 UTC, wangye805 commented on tests/pytorch/fused_attn/test_fused_attn_with_cp.py
> -@pytest.mark.skipif(device_count() < 2, reason="multi-GPU host is required")
Added back. Thanks.

2024-12-09 04:53 UTC, wangye805 commented on transformer_engine/jax/__init__.py
> +        ), "Could not find `transformer-engine-cu12`."
Do you mean transformer_engine_cu12? I don't think so. Based on my experience installing TE on jax, I don't think it will run into this line.

2024-12-09 04:54 UTC, wangye805 commented on transformer_engine/common/fused_attn_rocm/fused_attn_aotriton.cpp
> +  //TODO: release after AOTriton support support Multi-latent attention
Yeah, it's a terminology for when d_qk != d_v

2024-12-09 05:00 UTC, wangye805 commented on transformer_engine/jax/csrc/extensions/ffi.cpp
> +/*************************************************************************
Thanks. Added

2024-12-09 05:01 UTC, wangye805 commented on transformer_engine/pytorch/csrc/extensions/multi_tensor/multi_tensor_adam.cu
Added. Thanks.

2024-12-09 05:03 UTC, wangye805 commented on transformer_engine/pytorch/csrc/type_shim.h
> -constexpr uint32_t THREADS_PER_WARP = 32;
Due to some added header inclusion, this will conflict with https://github.com/ROCm/TransformerEngine/blob/2b6dc5f9f77572dcab27c0fc63a57fd502e44462/transformer_engine/common/utils.cuh#L47

2024-12-09 16:01 UTC, ipanfilo commented on build_tools/utils.py
> -import importlib.metadata
Does python -c "import importlib, re; any(re.match(r'jax-rocm\d+-plugin', d.metadata['Name']) for d in importlib.metadata.distributions())" work for you ? It didn't work for me either when this line was added or now.

2024-12-09 17:07 UTC, ipanfilo commented on tests/pytorch/fused_attn/test_fused_attn_with_cp.py
> +    if IS_HIP_EXTENSION and qkv_format == "thd":
Just note. If move HIP THD and HIP FP8 condition below above corresponding CUDA conditions, the latter do not need (not IS_HIP_EXTENSION)

2024-12-09 17:07 UTC, ipanfilo commented on transformer_engine/pytorch/csrc/type_shim.h
> -constexpr uint32_t THREADS_PER_WARP = 32;
If so, it can still be used below instead of hardcoding 32

2024-12-09 17:07 UTC, ipanfilo commented on transformer_engine/pytorch/csrc/extensions/multi_tensor/multi_tensor_adam.cu
> +#define THREADS_PER_WARP 32
It should be already declared in common/utils.cuh

2024-12-09 17:07 UTC, ipanfilo commented on qa/L0_pytorch_unittest/test.sh
> +pytest -v -s $TE_PATH/tests/pytorch/test_permutation.py
If test_permutation is supported on ROCm, it should be added to ci/pytorch.sh

2024-12-12 21:03 UTC, wangye805 commented on transformer_engine/pytorch/csrc/type_shim.h
> -constexpr uint32_t THREADS_PER_WARP = 32;
Okay, we will run into compilation error if we use this THREADS_PER_WARP instead of hard coding 32. 

1). If we put this constexpr in transformer_engine/pytorch/csrc/type_shim.h, we will have double definition in transformer_engine/pytorch/csrc/extensions/multi_tensor/multi_tensor_adam.cu as both line 19 and line 21 both contain this. 

2). If we do not put this constexpr in transformer_engine/pytorch/csrc/type_shim.h, then in transformer_engine/pytorch/csrc/extensions/multi_tensor/multi_tensor_scale_kernel.cu compilation, this keyword will not be define. 

See my following screenshot:
![image](https://github.com/user-attachments/assets/1e611f92-865f-4664-84b9-e5986cbf8071)

2024-12-12 21:07 UTC, wangye805 commented on build_tools/utils.py
> -import importlib.metadata
I can successfully install and ran this branch in jax dockers.

2024-12-12 22:59 UTC, ipanfilo commented on transformer_engine/pytorch/csrc/type_shim.h
> -constexpr uint32_t THREADS_PER_WARP = 32;
I see. If remove the constexpr from type_shim.h, it depends on utils.cuh but does not include the latter. And among pytorch/csrc/extensions/multi_tensor/* only multi_tensor_adam.cu includes utils.cuh to resolve.

One approach is add utils.cuh to type_shim.sh but because the latter is quite big constexpr uint can be replaced with #define THREADS_PER_WARP 32
Or, to keep it as const (for debug?):
#ifndef THREADS_PER_WARP
constexpr uint32_t THREADS_PER_WARP = 32;
#define THREADS_PER_WARP THREADS_PER_WARP
#endif

2024-12-13 00:19 UTC, ipanfilo commented on build_tools/utils.py
> -import importlib.metadata
I think I understood why: pip install loads importlib.metadata somewhere behind the curtains so when importlib is imported in utils.py, it already has metadata initialized.

2024-12-13 00:19 UTC, ipanfilo commented on ci/pytorch.sh
> +    run 1 test_permutation.py
please put it alphabetically to easier tracking

2024-12-18 22:20 UTC, wangye805 commented on tests/pytorch/fused_attn/test_fused_attn_with_cp.py
> +    if IS_HIP_EXTENSION and qkv_format == "thd":
I think we still need this (not IS_HIP_EXTENSION) condition since we also implemented get_device_compute_capability.  On MI300, this get_device_compute_capability will return (9, 4) since we are gfx942.

2024-12-18 22:23 UTC, wangye805 commented on transformer_engine/pytorch/csrc/extensions/multi_tensor/multi_tensor_adam.cu
> +#define THREADS_PER_WARP 32
I think we can keep this line to stay the same as our upstream NVTE, in order to reduce our future IFU efforts, as long as it does not causes issues.

2024-12-18 22:24 UTC, wangye805 commented on ci/pytorch.sh
> +    run 1 test_permutation.py
Addressed. Thanks

2024-12-18 22:26 UTC, wangye805 commented on transformer_engine/pytorch/csrc/type_shim.h
> -constexpr uint32_t THREADS_PER_WARP = 32;
I included "common/utils.cuh" into type_shim.h so the source codes look cleaner and compilation does not complain about the pro-processing

2024-12-19 02:25 UTC, ipanfilo commented on tests/pytorch/fused_attn/test_fused_attn_with_cp.py
> +    if IS_HIP_EXTENSION and qkv_format == "thd":
I mean that after (IS_HIP_EXTENSION and qkv_format == "thd") (qkv_format == "thd" and get_device_compute_capability()...) can only be true in CUDA case.

2024-12-19 02:34 UTC, ipanfilo approved these changes

2024-12-19 16:47 UTC, wangye805 commented on tests/pytorch/fused_attn/test_fused_attn_with_cp.py
> +    if IS_HIP_EXTENSION and qkv_format == "thd":
Which line are you referring to?
line 116 if condition "(not IS_HIP_EXTENSION) and qkv_format == "thd" and get_device_compute_capability() < (9, 0)" is for cuda
line 118 if condition "IS_HIP_EXTENSION and qkv_format == "thd"" is for rocm
I don't think one of them is redundant?

2024-12-19 17:04 UTC, ipanfilo commented on tests/pytorch/fused_attn/test_fused_attn_with_cp.py
> +    if IS_HIP_EXTENSION and qkv_format == "thd":
If you swap and make (IS_HIP_EXTENSION and qkv_format == "thd") firsts, then (qkv_format == "thd" and get_device_compute_capability() < (9, 0)) will only be evaluated in case of CUDA, i.e. (not IS_HIP_EXTENSION) is not necessary. You can represent it it as {if (qkv_format == "thd") { if (IS_HIP_EXTENSION) { skip };  if (/*not IS_HIP_EXTENSION is not needed here*/ get_device_capability...) skip }}

2024-12-23 16:08 UTC, ipanfilo requested changes

2024-12-23 16:08 UTC, ipanfilo commented on ci/jax.sh
> -    rc=$?
If we don't need install those components the below lines checking rc should also be removed

2024-12-23 16:08 UTC, ipanfilo commented on ci/jax.sh
> +    pip list | awk '/transformer_engine/ { print $1"=="$2}' >> requirements.in
This should be one awk call with line /jax|transformer_engine/
But why do we need it? Does Praxis depend on TE?

2024-12-23 16:08 UTC, ipanfilo commented on ci/jax.sh
> +}
Isn't Flax installed as Praxis prerequisite? Why do we need separate installation?
And please take care of reqs file. Which directory is it created in?

2024-12-23 16:58 UTC, wangye805 commented on tests/pytorch/fused_attn/test_fused_attn_with_cp.py
> +    if IS_HIP_EXTENSION and qkv_format == "thd":
Addressed. Thanks

2024-12-23 16:58 UTC, wangye805 commented on ci/jax.sh
> -    rc=$?
Removed. Thanks

2024-12-23 17:00 UTC, wangye805 commented on ci/jax.sh
> +    pip list | awk '/transformer_engine/ { print $1"=="$2}' >> requirements.in
Thanks for your comments. I'm not quite familiar with awk usage. Can you show me how to write two awk into one line? 

The reason I add "transformer_engine==1.11.0" into requirements.in: if I don't add it, the pydantic version will mismatch and will cause some jax pytest failures.

2024-12-23 17:01 UTC, wangye805 commented on ci/jax.sh
> +}
Removed it. Let me see whether it can pass the CI. Thanks

2024-12-23 20:16 UTC, ipanfilo commented on ci/jax.sh
> +    pip list | awk '/transformer_engine/ { print $1"=="$2}' >> requirements.in
Ok then. Can you add comments that transformer engine is added to keep its dependencies and merge both lines to one with /jax|transformer_engine/ instead of separate /jax/ and /tansformer_engine/

2024-12-25 04:46 UTC, wangye805 commented on ci/jax.sh
> +    pip list | awk '/transformer_engine/ { print $1"=="$2}' >> requirements.in
Combined jax and transformer_engine in one awk line. Thanks Ilya for your suggestion!

2024-12-25 17:33 UTC, ipanfilo approved these changes

2024-12-25 21:30 UTC, merged