Ipanfilo/fa support
ROCm/TransformerEngine pull request #96
Opened 2024-12-04 15:21 UTC by ipanfilo

# Description

This is work-in-progress review for ROCm FlashAttn2 support

Fixes #[9693](https://github.com/ROCm/frameworks-internal/issues/9693)

## Type of change

- [ ] New feature (non-breaking change which adds functionality)

## Changes

- Enable FA specific code on ROCm platforms
- Cherry-pick upstream TE changes needed for proper FA working
- Modify test scripts to accommodate new FA

2025-01-09 22:18 UTC, wenchenvincent commented on ci/_utils.sh
> +            unset NVTE_FLASH_ATTN
I think we want to `export NVTE_FLASH_ATTN=1` here?

2025-01-09 22:22 UTC, wenchenvincent commented on tests/pytorch/fused_attn/test_fused_attn_with_cp.py
> +    _flash_attn_2_6_plus,
It seems that this is not used in this file?

2025-01-10 00:36 UTC, ipanfilo commented on ci/_utils.sh
> +            unset NVTE_FLASH_ATTN
All NVTE_FLASH_ATTN and NVTE_FUSED_ATTN* are "1" by default so unset is equivalent to set 1

2025-01-10 00:37 UTC, ipanfilo commented on tests/pytorch/fused_attn/test_fused_attn_with_cp.py
> +    _flash_attn_2_6_plus,
Oh, yes. It left from pre IFU 1.11 commit where THD was only skipped with 2.6+

2025-01-10 18:59 UTC, wenchenvincent commented on tests/pytorch/fused_attn/test_fused_attn_with_cp.py
> +    _flash_attn_2_6_plus,
Oh, also, I think we need to merge the updates from the dev branch (now with IFU 1.11) to make sure there is no breakage from that.

2025-01-10 22:49 UTC, ipanfilo commented on tests/pytorch/fused_attn/test_fused_attn_with_cp.py
> +    _flash_attn_2_6_plus,
It has those changes

2025-02-03 22:53 UTC, wangye805 requested changes
By the way, how about the dropout seed offset issue in flash-attn package?

2025-02-03 22:53 UTC, wangye805 commented on tests/pytorch/test_numerics.py
> +    @cache
What's the difference between lru_cache and cache? Why do we need to change it from lru_cache to cache?

2025-02-03 22:53 UTC, wangye805 commented on README.rst
> +* Attention (Flash Attention, Fused Multihead Attention): partially supported: Fused Attention with AOTriton and CK backends, FlashAttention-2 with fixed length sequences
nit: usually we don't say fixed length sequences in flash-attn/fused-attn. We can change to FlashAttention-2 without variable sequence length feature

2025-02-03 22:53 UTC, wangye805 commented on transformer_engine/pytorch/attention.py
> -            # ROCm TE can support generic sliding window with dropout
This PR is about flash-attn. Why do we change use_fused_attntion?

2025-02-03 22:53 UTC, wangye805 commented on transformer_engine/pytorch/attention.py
> +        use_flash_attention and (not IS_HIP_EXTENSION)
Do we have similar logic to prefer fused attn or flash attn?

2025-02-04 05:18 UTC, ipanfilo commented on tests/pytorch/test_numerics.py
> +    @cache
@cache is python 3.9 feature, which should be lighter than lru_cache: https://stackoverflow.com/questions/70301475/difference-between-functools-cache-and-lru-cache
It is not critical. The rest of test_numerics does not use caches so I eventually removed it too not to import something just for HIP

2025-02-04 05:28 UTC, ipanfilo commented on transformer_engine/pytorch/attention.py
> -            # ROCm TE can support generic sliding window with dropout
I think it was discussed some time ago. This code duplicates code on line 451 that is more generic. If you like, I can make it separate PR

2025-02-04 05:30 UTC, ipanfilo commented on transformer_engine/pytorch/attention.py
> +        use_flash_attention and (not IS_HIP_EXTENSION)
We use generic logic which prefers flash attention over fused attention

2025-02-04 15:17 UTC, wangye805 commented on tests/pytorch/test_numerics.py
> +    @cache
Got it. Thanks

2025-02-04 15:20 UTC, wangye805 commented on transformer_engine/pytorch/attention.py
> -            # ROCm TE can support generic sliding window with dropout
Oh, I see line 451. Yeah, you are right. Let's include your change in this PR.

2025-02-04 15:32 UTC, wangye805 commented on transformer_engine/pytorch/attention.py
> +        use_flash_attention and (not IS_HIP_EXTENSION)
Do you mean https://github.com/ROCm/TransformerEngine/blob/e877c03bf662b4889458ba09c73a01e23100dad3/transformer_engine/pytorch/attention.py#L878? 

I saw in line https://github.com/ROCm/TransformerEngine/blob/e877c03bf662b4889458ba09c73a01e23100dad3/transformer_engine/pytorch/attention.py#L850, NV prefer cudnn fused attn "f16_arbitrary_seqlen" over flash attn for performance reason. Maybe later we can try to benchmark which one is better for us in ROCm

2025-02-04 16:00 UTC, ipanfilo commented on transformer_engine/pytorch/attention.py
> +        use_flash_attention and (not IS_HIP_EXTENSION)
They do it for specific workload and GPU. Yes, we could do the same but currently we don't even have a list of critical workloads and what is model GPU

2025-02-04 16:25 UTC, wangye805 approved these changes
LGTM

2025-02-04 21:58 UTC, merged